In [2]:
x=[1,2,3,4,5]

In [3]:
for i in x:
    print(i*10)

10
20
30
40
50


In [5]:
# looping
x10=[]
for i in x:
    x10.append(i*10)
x10

[10, 20, 30, 40, 50]

In [7]:
# comprehension
xcube= [i**3 for i in x]
xcube

[1, 8, 27, 64, 125]

In [8]:
# Lambda
# f(x) = x * 3
f= lambda x: x * 3

In [9]:
f(5)

15

In [10]:
x7 = list(map(lambda x: x - 3, x10))
x7

[7, 17, 27, 37, 47]

In [11]:
import numpy as np

In [20]:
x= np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [21]:
y=np.array([[20],[30],[40],[50]])
print(y)

[[20]
 [30]
 [40]
 [50]]


In [22]:
x.reshape(1,-1)

array([[1, 2, 3, 4, 5]])

In [23]:
z=np.random.randint(1,100,(8,8))
print(z)

[[68 29 40  8 66 33 25 20]
 [96 76 73 55 48 13 44 89]
 [47  7 19 51 47 42 92 77]
 [66 96 88 55  8 66 20 52]
 [85 90 50  7  4 71  3 25]
 [76 13  8 34 15 26 21 99]
 [17  6 45 75 10 30 39 16]
 [27 14 97 45 43 11 10 80]]


# Syntax of slicing
`arr[rowstart : rowend , colstart : colend]`

In [25]:
z[:,-1] #last col

array([20, 89, 77, 52, 25, 99, 16, 80])

In [26]:
z[-1,:] #last row

array([27, 14, 97, 45, 43, 11, 10, 80])

In [27]:
z[:,:-1] # all col except last

array([[68, 29, 40,  8, 66, 33, 25],
       [96, 76, 73, 55, 48, 13, 44],
       [47,  7, 19, 51, 47, 42, 92],
       [66, 96, 88, 55,  8, 66, 20],
       [85, 90, 50,  7,  4, 71,  3],
       [76, 13,  8, 34, 15, 26, 21],
       [17,  6, 45, 75, 10, 30, 39],
       [27, 14, 97, 45, 43, 11, 10]])

In [28]:
z[:6,:]

array([[68, 29, 40,  8, 66, 33, 25, 20],
       [96, 76, 73, 55, 48, 13, 44, 89],
       [47,  7, 19, 51, 47, 42, 92, 77],
       [66, 96, 88, 55,  8, 66, 20, 52],
       [85, 90, 50,  7,  4, 71,  3, 25],
       [76, 13,  8, 34, 15, 26, 21, 99]])

In [29]:
z[:6,3:]

array([[ 8, 66, 33, 25, 20],
       [55, 48, 13, 44, 89],
       [51, 47, 42, 92, 77],
       [55,  8, 66, 20, 52],
       [ 7,  4, 71,  3, 25],
       [34, 15, 26, 21, 99]])

In [30]:
z.max()

99

In [33]:
x=np.random.randn(10)
x

array([ 0.13352989, -0.28173698, -0.47146345, -1.28117499, -0.34087836,
        1.40121285,  0.27886389,  0.40706588,  0.70023911,  1.36145432])

In [35]:
x.argmax()

5

In [36]:
import pandas as pandas
import seaborn as sns

In [37]:
df=sns.load_dataset('titanic')

In [38]:
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [39]:
df.fare.apply(lambda val : round(val))

0       7
1      71
2       8
3      53
4       8
       ..
886    13
887    30
888    23
889    30
890     8
Name: fare, Length: 891, dtype: int64